/*
	Vehicle & backpack Paintshop
	By Halv
	
	Copyright (C) 2015  Halvhjearne > README.md
*/
//these are the classnames of buildings that will activate the paintshop
_paintshopbuildings = ["Land_CarService_F","Land_Repair_center"];
//add textures and preset colors here
_textures = [
//default arma 3 textures
	/*["Debriefing background","\a3\Ui_f\data\gui\cfg\Debriefing\debriefingbackground_co.paa"],
	["CommunityGuide background 1","\a3\Ui_f\data\gui\cfg\CommunityGuide\airassault_co.paa"],
	["CommunityGuide background 2","\a3\Ui_f\data\gui\cfg\CommunityGuide\basicinfantrycombat_co.paa"],
	["CommunityGuide background 3","\a3\Ui_f\data\gui\cfg\CommunityGuide\combinedarms_co.paa"],
	["CommunityGuide background 4","\a3\Ui_f\data\gui\cfg\CommunityGuide\groundvehiclecrew_co.paa"],
	["CommunityGuide background 5","\a3\Ui_f\data\gui\cfg\CommunityGuide\guerrillawarfare_co.paa"],
	["CommunityGuide background 6","\a3\Ui_f\data\gui\cfg\CommunityGuide\helicopters_co.paa"],
	["CommunityGuide background 7","\a3\Ui_f\data\gui\cfg\CommunityGuide\introduction_co.paa"],
	["CommunityGuide background 8","\a3\Ui_f\data\gui\cfg\CommunityGuide\sniperslaunchers_co.paa"],
	["CommunityGuide background 9","\a3\Ui_f\data\gui\cfg\CommunityGuide\zeus_co.paa"],
	["LoadingScreens 1","\a3\Ui_f\data\gui\cfg\LoadingScreens\gc_wallpaper_06_co.paa"],
	["LoadingScreens 2","\a3\Ui_f\data\gui\cfg\LoadingScreens\gc_wallpaper_07_co.paa"],
	["LoadingScreens 3","\a3\Ui_f\data\gui\cfg\LoadingScreens\gc_wallpaper_10_co.paa"],
	["LoadingScreens 4","\a3\Ui_f\data\gui\cfg\LoadingScreens\gc_wallpaper_14_co.paa"],
	["LoadingScreens 5","\a3\Ui_f\data\gui\cfg\LoadingScreens\gc_wallpaper_16_co.paa"],
	["LoadingScreens 6","\a3\Ui_f\data\gui\cfg\LoadingScreens\gc_wallpaper_17_co.paa"],
	["LoadingScreens 7","\a3\Ui_f\data\gui\cfg\LoadingScreens\gc_wallpaper_18_co.paa"],
	["LoadingScreens 8","\a3\Ui_f\data\gui\cfg\LoadingScreens\loading_01_co.paa"],
	["Bootcamp Background","\a3\Ui_f\data\gui\Rsc\RscDisplayBootcampMsgBox\bootcampmsgbox_background_ca.paa"],
	["Workshop defaultimage","\a3\Ui_f\data\gui\Rsc\RscDisplayPublishMission\steamworksdefaultimage_co.paa"],
	["WelcomeScreens 1","\a3\Ui_f\data\gui\Rsc\RscDisplayWelcome\welcome1_ca.paa"],
	["WelcomeScreens 2","\a3\Ui_f\data\gui\Rsc\RscDisplayWelcome\welcome2_ca.paa"],
	["WelcomeScreens 3","\a3\Ui_f\data\gui\Rsc\RscDisplayWelcome\welcome3_ca.paa"],
	["WelcomeScreens 4","\a3\Ui_f\data\gui\Rsc\RscDisplayWelcome\welcome4_ca.paa"],
//karts pics
	["Karts Content","\a3\data_f_kart\images\karts_contentbrowserpicture_co.paa"],
	["Karts illustration 1","\a3\data_f_kart\images\karts_illustration_01_ca.paa"],
	["Karts illustration 2","\a3\data_f_kart\images\karts_illustration_02_ca.paa"],
	["Karts illustration 3","\a3\data_f_kart\images\karts_illustration_03_ca.paa"],
	["Karts illustration 4","\a3\data_f_kart\images\karts_illustration_04_ca.paa"],
	["Karts illustration 5","\a3\data_f_kart\images\karts_illustration_05_ca.paa"],
	["Karts illustration 6","\a3\data_f_kart\images\karts_illustration_06_ca.paa"],
	["Karts Overview","\a3\data_f_kart\images\karts_overviewpicture_co.paa"],
	["Karts Flag 1","\a3\data_f_kart\Flags\flag_bluking1_co.paa"],
	["Karts Flag 2","\a3\data_f_kart\Flags\flag_bluking2_co.paa"],
	["Karts Flag 3","\a3\data_f_kart\Flags\flag_fuel1_co.paa"],
	["Karts Flag 4","\a3\data_f_kart\Flags\flag_fuel2_co.paa"],
	["Karts Flag 5","\a3\data_f_kart\Flags\flag_koke1_co.paa"],
	["Karts Flag 6","\a3\data_f_kart\Flags\flag_koke2_co.paa"],
	["Karts Flag 7","\a3\data_f_kart\Flags\flag_redburger_co.paa"],
	["Karts Flag 8","\a3\data_f_kart\Flags\flag_redstone_co.paa"],
	["Karts Flag 9","\a3\data_f_kart\Flags\flag_suatmm_co.paa"],
//Epoch
	["Bear","\x\addons\a3_epoch_assets\textures\bear\bear_co.paa"],
	["Candy","\x\addons\a3_epoch_assets\textures\candy\candy_ca.paa"],
	["Circuit","\x\addons\a3_epoch_assets\textures\circuit\circuit_co.paa"],
	["Concrete","\x\addons\a3_epoch_assets\textures\concrete_ca.paa"],
	["Wood","\x\addons\a3_epoch_assets\textures\wood_co.paa"],
	["Supply crate","\x\addons\a3_epoch_assets_1\textures\supply_crate_co.paa"],
	["Carry Tent","\x\addons\a3_epoch_assets_3\carnival\carnyTent_co.paa"],
//other
	["Heli Content","\a3\data_f_heli\images\heli_overviewpicture_co.paa"],
	["Eagle","\a3\data_f_curator\Eagle\Data\eagle_co.paa"],*/
//preset colors
	//["Red","#(argb,8,8,3)color(1,0,0,1)"],
	//["Green","#(argb,8,8,3)color(0,1,0,1)"],
	//["Blue","#(argb,8,8,3)color(0,0,1,1)"],
	//["Black","#(argb,8,8,3)color(0,0,0,0.6)"],
	//["Pink","#(argb,8,8,3)color(1,0.75,0.84,0.2)"],
	//["Tan","#(argb,8,8,3)color(0.8,0.7,0.5,0.2)"],
//custom textures (have to be in your mission pbo)
	//["AAF","\standarol_client\media\textures\main\aaf.paa"],
	["Blood","\standarol_client\media\textures\main\blood.paa"],
	["Blood Shot","\standarol_client\media\textures\main\bloodshot.paa"],
	["Blue Lines","\standarol_client\media\textures\main\bluelines.paa"],
	["Blue Circles","\standarol_client\media\textures\main\blue-circles.paa"],
	["Board","\standarol_client\media\textures\main\board.paa"],
	["Bowtie Pasta","\standarol_client\media\textures\main\bowtie_pasta.paa"],
	["Camo Orange","\standarol_client\media\textures\main\camo_orange.paa"],
	["Camo Pink","\standarol_client\media\textures\main\camo_pink.paa"],
	["Camo Red","\standarol_client\media\textures\main\camo_red.paa"],
	["Carbon","\standarol_client\media\textures\main\carbon.paa"],
	["Circuit","\standarol_client\media\textures\main\circuit2.paa"],
	["Color Pattern #1","\standarol_client\media\textures\main\colorpattern1.paa"],
	["Color Pattern #2","\standarol_client\media\textures\main\colorpattern2.paa"],
	["Color Pattern #3","\standarol_client\media\textures\main\colorpattern3.paa"],
	["Color Pattern #4","\standarol_client\media\textures\main\colorpattern4.paa"],
	["Color Pattern #5","\standarol_client\media\textures\main\colorpattern5.paa"],
	["Color Pattern #6","\standarol_client\media\textures\main\colorpattern6.paa"],
	["Color Wall","\standarol_client\media\textures\main\colors_wall.paa"],
	["Confederate","\standarol_client\media\textures\main\confederate.paa"],
	["Cracked Earth","\standarol_client\media\textures\main\crackedearth.paa"],
	//["Csat","\standarol_client\media\textures\main\csat.paa"],
	["Desert Camo","\standarol_client\media\textures\main\denim.paa"],
	["Denim","\standarol_client\media\textures\main\desertcamo.paa"],
	["Digital","\standarol_client\media\textures\main\digi.paa"],
	["Digital Black","\standarol_client\media\textures\main\digi_black.paa"],
	["Digital Blue","\standarol_client\media\textures\main\digital_blue.paa"],
	["Digital China","\standarol_client\media\textures\main\digitalchina.paa"],
	["Digi Desert","\standarol_client\media\textures\main\digi_desert.paa"],
	["Digi Wood","\standarol_client\media\textures\main\digi_wood.paa"],
	["Drylands","\standarol_client\media\textures\main\drylands.paa"],
	["Flowers","\standarol_client\media\textures\main\flowers.paa"],
	["Flowers Pattern","\standarol_client\media\textures\main\flowers-pattern.paa"],
	["Green Mosaic","\standarol_client\media\textures\main\greenmosaic.paa"],
	["Grunge","\standarol_client\media\textures\main\grunge.paa"],
	["Hello Kitty","\standarol_client\media\textures\main\hellokitty.paa"],
	["Hex","\standarol_client\media\textures\main\hex.paa"],
	["Hexagons","\standarol_client\media\textures\main\hexagon.paa"],
	["Hippie","\standarol_client\media\textures\main\hippie.paa"],
	["Lava","\standarol_client\media\textures\main\lava.paa"],
	["Leaf","\standarol_client\media\textures\main\leaf.paa"],
	["Liquens","\standarol_client\media\textures\main\liquens.paa"],
	["Leopard","\standarol_client\media\textures\main\leopard.paa"],
	["Love","\standarol_client\media\textures\main\love.paa"],
	["Military #1","\standarol_client\media\textures\main\military1.paa"],
	["Military #2","\standarol_client\media\textures\main\military2.paa"],
	["Military #3","\standarol_client\media\textures\main\military3.paa"],
	["Military #4","\standarol_client\media\textures\main\military4.paa"],
	["Military #5","\standarol_client\media\textures\main\military5.paa"],
	["Military #6","\standarol_client\media\textures\main\military6.paa"],
	["Military #7","\standarol_client\media\textures\main\military7.paa"],
	["Military #8","\standarol_client\media\textures\main\military8.paa"],
	["Military #9","\standarol_client\media\textures\main\military9.paa"],
	["Military #10","\standarol_client\media\textures\main\military10.paa"],
	["Military #11","\standarol_client\media\textures\main\military11.paa"],
	["Military #12","\standarol_client\media\textures\main\military12.paa"],
	["Military Blue","\standarol_client\media\textures\main\militaryblue.paa"],
	["Military Classic","\standarol_client\media\textures\main\militaryclassic.paa"],
	["Military Pattern","\standarol_client\media\textures\main\militarypattern.paa"],
	["Orange Leaves","\standarol_client\media\textures\main\orange_leaves.paa"],
	["Paper","\standarol_client\media\textures\main\paper.paa"],
	["Plastic Blue","\standarol_client\media\textures\main\plastic-blue.paa"],
	["Pride","\standarol_client\media\textures\main\pride.paa"],
	["Purple Woven","\standarol_client\media\textures\main\purple-woven.paa"],
	["Red Clouds","\standarol_client\media\textures\main\red-clouds.paa"],
	["Red Sand","\standarol_client\media\textures\main\red_text.paa"],
	["Red Stripes","\standarol_client\media\textures\main\red-stripes.paa"],
	["Rusty","\standarol_client\media\textures\main\rusty.paa"],
	["Sand","\standarol_client\media\textures\main\sand.paa"],
	["Snake","\standarol_client\media\textures\main\snake.paa"],
	["Stripes","\standarol_client\media\textures\main\stripes.paa"],
	["Stripes 2","\standarol_client\media\textures\main\stripes2.paa"],
	["Stripes 3","\standarol_client\media\textures\main\stripes3.paa"],
	["Stripes 4","\standarol_client\media\textures\main\stripes4.paa"],
	["Stripes 5","\standarol_client\media\textures\main\stripes5.paa"],
	["Stripes 6","\standarol_client\media\textures\main\stripes6.paa"],
	["Stripes 7","\standarol_client\media\textures\main\stripes7.paa"],
	["Swamp","\standarol_client\media\textures\main\swamp.paa"],
	["Tiger","\standarol_client\media\textures\main\tiger.paa"],
	["Triangles","\standarol_client\media\textures\main\triangles.paa"],
	["Unionjack","\standarol_client\media\textures\main\unionjack.paa"],
	["Urban","\standarol_client\media\textures\main\urban.paa"],
	["Vibrant Pattern","\standarol_client\media\textures\main\vibrant-pattern.paa"],
	["Wall","\standarol_client\media\textures\main\wall.paa"],
	["Wall #2","\standarol_client\media\textures\main\wall2.paa"],
	["Waves Stripes","\standarol_client\media\textures\main\wavesstripes.paa"],
	["Weed","\standarol_client\media\textures\main\weed.paa"],
	["Wood Dark","\standarol_client\media\textures\main\wooddark.paa"],
	["Wood Land","\standarol_client\media\textures\main\woodland.paa"],
	["Wood Tiger","\standarol_client\media\textures\main\woodtiger.paa"],
	["Zebra","\standarol_client\media\textures\main\zebra.paa"],
	["1943","\standarol_client\media\textures\main\1943.paa"]
];